# .github/workflows/ci-cd.yml
on:
  push:
    branches:
      - main

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://pypi.org/p/conv_html_to_markdown/
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    # retrieve your distributions here

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@v1.8.11