# .github/workflows/pypi-publish.yml
on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://pypi.org/p/conv_html_to_markdown/
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:


    # Publish the package to PyPI
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@v1.8.11